### ISSUE TITLE
demo / examples database issue

### ISSUE THREAD

**Issue by sanjayminni** [yannij/MaterialComponentsWeb#10]
on loading as outlined in issue#9
tidbit\todo does not login with guest/secret
tidbit\loanex login works and shows expected results
however if tidbit\todo login is smoehow repaired using a combination of recover login, recover database etc then tidbit\todo login starts and shows expected results but loanex login stops or does not show any existing data (guest/secret)

**Comment by yannij** [comment]
Change to use separate memory repository for each sample app, instead of using the singleton repo
