### ISSUE TITLE
tab-based navigation issues in Shrine demo for tablet -sized layout

### ISSUE THREAD

**Issue by sanjayminni** [yannij/MaterialComponentsWeb#8]
there are 2 issues

1. there is no indicator on the current tab active (by way of a line below or tab colour change - hence it is not clear which tab is active. I had faced this problem when i had tried to include this feature in my app cloned from material/auto-responsive by cloning the code from material/nav-tabs

2. it may be preferred if topAppBar collapse feature is disabled in this mode

**Comment by yannij** [comment]
Code change published: "Change MDSLayoutTopAppBarTabs ignores the collapse action for the top app bar. Also, the MDSLayoutExampleApp is modified so the tab indicator is visible"
