### ISSUE TITLE
Installation related issues

### ISSUE THREAD

**Issue by sanjayminni** [yannij/MaterialComponentsWeb#9]
Loading throws up error:
![MCW-LoadingError](https://user-images.githubusercontent.com/12030766/139814472-4025cb78-cc73-4272-b5d8-276c3158c95f.jpg)
 
to get around load tidbit first.
and then to get material demos load package material-demo manually
and then to get the configuration on study-* in seaside - unload material-study and load material-study again

**Comment by yannij** [comment]
Eliminate the forward reference to Tidbit class. Note that problem only shows up when building MaterialComponentsWeb directly. When building Tidbit, the forward reference is masked, because the needed class is eventually loaded
